2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_setup.py:_flush():67] Configure stats pid to 797794
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_setup.py:_flush():67] Loading settings from /home/daniel/.config/wandb/settings
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_setup.py:_flush():67] Loading settings from /home/daniel/workspace/actuator_modeling/wandb/settings
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250326_123448-b9r5lk4e/logs/debug.log
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250326_123448-b9r5lk4e/logs/debug-internal.log
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_init.py:init():761] calling init triggers
2025-03-26 12:34:48,213 INFO    MainThread:797794 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'model': '../model/mlp.yaml', 'data': '../data/actuator_data.yaml', 'batch_size': 64, 'learning_rate': 0.001, 'weight_decay': 1e-05, 'max_epochs': 100, 'patience': 10, 'num_workers': 4, 'log_frequency': 50, 'val_check_interval': 1.0, 'wandb': {'project_name': 'actuator-modeling'}, 'hidden_dims': [64, 128, 256, 128, 64], 'activation': 'relu', 'dropout': 0.1, 'use_batch_norm': True, 'use_residual': True, 'data_filename': 'actuator_data.csv', 'radius_to_accelerometer_center': 0.033, 'control_frequency': 50.0, 'inertia': 1.0, 'split_ratio': 0.8, 'seed': 42, '_wandb': {}}
2025-03-26 12:34:48,214 INFO    MainThread:797794 [wandb_init.py:init():784] starting backend
2025-03-26 12:34:48,214 INFO    MainThread:797794 [wandb_init.py:init():788] sending inform_init request
2025-03-26 12:34:48,219 INFO    MainThread:797794 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-26 12:34:48,220 INFO    MainThread:797794 [wandb_init.py:init():798] backend started and connected
2025-03-26 12:34:48,223 INFO    MainThread:797794 [wandb_init.py:init():891] updated telemetry
2025-03-26 12:34:48,223 INFO    MainThread:797794 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-26 12:34:48,853 INFO    MainThread:797794 [wandb_init.py:init():990] starting run threads in backend
2025-03-26 12:34:48,858 ERROR   MainThread:797794 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1031, in init
    run._on_start()
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2398, in _on_start
    self._header(settings=self._settings, printer=self._printer)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 3746, in _header
    Run._header_run_info(settings=settings, printer=printer)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 3829, in _header_run_info
    printer.display(
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/printer.py", line 305, in display
    self._display_fn_mapping(level)(text)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/errors/term.py", line 172, in termlog
    _log(
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/errors/term.py", line 358, in _log
    click.echo(string, file=sys.stderr, nl=newline)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/click/utils.py", line 318, in echo
    file.write(out)  # type: ignore
    ^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/console_capture.py", line 147, in write_with_callbacks
    n = orig_write(s)
        ^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-03-26 12:34:49,859 INFO    MsgRouterThr:797794 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
