2025-05-28 14:44:58,218 INFO    MainThread:1334355 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-05-28 14:44:58,218 INFO    MainThread:1334355 [wandb_setup.py:_flush():67] Configure stats pid to 1334355
2025-05-28 14:44:58,218 INFO    MainThread:1334355 [wandb_setup.py:_flush():67] Loading settings from /home/daniel/.config/wandb/settings
2025-05-28 14:44:58,218 INFO    MainThread:1334355 [wandb_setup.py:_flush():67] Loading settings from /home/daniel/workspace/actuator_modeling/wandb/settings
2025-05-28 14:44:58,218 INFO    MainThread:1334355 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-28 14:44:58,218 INFO    MainThread:1334355 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/daniel/workspace/actuator_modeling/outputs/2025-05-28/14-44-57/wandb/run-20250528_144458-lpk6lkbw/logs/debug.log
2025-05-28 14:44:58,219 INFO    MainThread:1334355 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/daniel/workspace/actuator_modeling/outputs/2025-05-28/14-44-57/wandb/run-20250528_144458-lpk6lkbw/logs/debug-internal.log
2025-05-28 14:44:58,219 INFO    MainThread:1334355 [wandb_init.py:init():761] calling init triggers
2025-05-28 14:44:58,219 INFO    MainThread:1334355 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'debug': False, 'seed': 42, 'evaluation_mode': 'global', 'work_dir': '/home/daniel/workspace/actuator_modeling', 'outputs_dir': '/home/daniel/workspace/actuator_modeling/outputs/2025-05-28/14-44-57', 'wandb': {'active': True, 'project': 'actuator_modeling_gru_v2', 'entity': '', 'name_suffix': 'debug', 'group_suffix': 'initial_tests', 'watch_log_freq': 100}, 'data': {'_target_': 'src.data.datamodule.ActuatorDataModule', 'dataset_configs': [{'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_0.csv', 'inertia': 0.01}, {'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_1.csv', 'inertia': 0.015}, {'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_2.csv', 'inertia': 0.02}], 'target_name': 'tau_measured', 'gyro_axis_for_ang_vel': 'Gyro_Z', 'accel_axis_for_torque': 'Acc_Y', 'batch_size': 32, 'num_workers': 4, 'seed': 42, 'global_train_ratio': 0.7, 'global_val_ratio': 0.15, 'fallback_sampling_frequency': 100.0, 'radius_accel': 0.2, 'radius_load': 0.3}, 'model': {'model_type': {'name': 'gru'}, '_target_': 'src.models.model.ActuatorModel', 'learning_rate': 0.001, 'weight_decay': 1e-06, 'warmup_epochs': 1, 'use_residual': False, 'k_spring': 0.0, 'theta0': 0.0, 'kp_phys': 0.0, 'kd_phys': 0.0, 'loss_diff_weight': 0.1, 'mlp_hidden_dims': [64, 128, 64], 'mlp_activation': 'relu', 'mlp_dropout': 0.1, 'mlp_use_batch_norm': True, 'gru_hidden_dim': 128, 'gru_num_layers': 2, 'gru_dropout': 0.1}, 'train': {'model': '../model/mlp.yaml', 'data': '../data/actuator_data.yaml', 'batch_size': 32, 'learning_rate': 0.001, 'weight_decay': 1e-06, 'max_epochs': 200, 'patience': 20, 'num_workers': 4, 'log_frequency': 50, 'val_check_interval': 1.0, 'wandb': {'project_name': 'actuator-modeling'}, 'accelerator': 'auto', 'devices': 1, 'precision': '32-true', 'early_stopping': {'active': True, 'monitor': 'val_rmse_epoch', 'mode': 'min', 'patience': 20, 'min_delta': 0.0001, 'verbose': True, 'stopping_threshold': None}, 'checkpointing': {'monitor': 'val_rmse_epoch', 'mode': 'min', 'save_top_k': 1, 'filename': 'best_model-{epoch:02d}-{val_rmse_epoch:.4f}'}, 'deterministic_trainer': True, 'gradient_clip_val': 5.0, 'gradient_clip_algorithm': 'norm', 'callbacks': {'learning_rate_monitor': True, 'early_summary': False, 'test_prediction_plotter': True}}, '_wandb': {}}
2025-05-28 14:44:58,219 INFO    MainThread:1334355 [wandb_init.py:init():784] starting backend
2025-05-28 14:44:58,219 INFO    MainThread:1334355 [wandb_init.py:init():788] sending inform_init request
2025-05-28 14:44:58,225 INFO    MainThread:1334355 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-28 14:44:58,225 INFO    MainThread:1334355 [wandb_init.py:init():798] backend started and connected
2025-05-28 14:44:58,229 INFO    MainThread:1334355 [wandb_init.py:init():891] updated telemetry
2025-05-28 14:44:58,235 INFO    MainThread:1334355 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-05-28 14:44:58,975 INFO    MainThread:1334355 [wandb_init.py:init():990] starting run threads in backend
2025-05-28 14:44:59,111 INFO    MainThread:1334355 [wandb_run.py:_console_start():2375] atexit reg
2025-05-28 14:44:59,111 INFO    MainThread:1334355 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-28 14:44:59,112 INFO    MainThread:1334355 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-28 14:44:59,112 INFO    MainThread:1334355 [wandb_run.py:_redirect():2315] Redirects installed.
2025-05-28 14:44:59,114 INFO    MainThread:1334355 [wandb_init.py:init():1032] run started, returning control to user process
2025-05-28 14:44:59,115 INFO    MainThread:1334355 [wandb_watch.py:_watch():71] Watching
2025-05-28 14:44:59,426 INFO    MainThread:1334355 [wandb_run.py:_config_callback():1261] config_cb None None {'model_type': 'gru', 'input_dim': 3, 'mlp_hidden_dims': [64, 128, 64], 'mlp_activation': 'relu', 'mlp_dropout': 0.1, 'mlp_use_batch_norm': True, 'gru_hidden_dim': 128, 'gru_num_layers': 2, 'gru_dropout': 0.1, 'learning_rate': 0.001, 'weight_decay': 1e-06, 'use_residual': False, 'k_spring': 0.0, 'theta0': 0.0, 'kp_phys': 0.0, 'kd_phys': 0.0, 'loss_diff_weight': 0.1, 'warmup_epochs': 1, '_target_': 'src.models.model.ActuatorModel', 'dataset_configs': "[{'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_0.csv', 'inertia': 0.01}, {'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_1.csv', 'inertia': 0.015}, {'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_2.csv', 'inertia': 0.02}]", 'radius_accel': 0.2, 'gyro_axis_for_ang_vel': 'Gyro_Z', 'accel_axis_for_torque': 'Acc_Y', 'target_name': 'tau_measured', 'batch_size': 32, 'num_workers': 4, 'global_train_ratio': 0.7, 'global_val_ratio': 0.15, 'seed': 42, 'fallback_sampling_frequency': 100.0, 'radius_load': 0.3}
2025-05-28 14:48:20,991 INFO    MainThread:1334355 [wandb_run.py:_config_callback():1261] config_cb None None {'model_type': 'gru', 'input_dim': 3, 'mlp_hidden_dims': [64, 128, 64], 'mlp_activation': 'relu', 'mlp_dropout': 0.1, 'mlp_use_batch_norm': True, 'gru_hidden_dim': 128, 'gru_num_layers': 2, 'gru_dropout': 0.1, 'learning_rate': 0.001, 'weight_decay': 1e-06, 'use_residual': False, 'k_spring': 0.0, 'theta0': 0.0, 'kp_phys': 0.0, 'kd_phys': 0.0, 'loss_diff_weight': 0.1, 'warmup_epochs': 1, '_target_': 'src.models.model.ActuatorModel', 'dataset_configs': "[{'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_0.csv', 'inertia': 0.01}, {'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_1.csv', 'inertia': 0.015}, {'csv_file_path': 'data/synthetic_raw/synthetic_actuator_data_mass_2.csv', 'inertia': 0.02}]", 'radius_accel': 0.2, 'gyro_axis_for_ang_vel': 'Gyro_Z', 'accel_axis_for_torque': 'Acc_Y', 'target_name': 'tau_measured', 'batch_size': 32, 'num_workers': 4, 'global_train_ratio': 0.7, 'global_val_ratio': 0.15, 'seed': 42, 'fallback_sampling_frequency': 100.0, 'radius_load': 0.3}
2025-05-28 14:48:22,119 INFO    MsgRouterThr:1334355 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-05-28 14:48:23,834 ERROR   MainThread:1334355 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-05-28 14:48:23,837 ERROR   MainThread:1334355 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
